### PR TITLE
Improve toplevel structure

### PR DESCRIPTION
**Pull request by iJustLeyxo**
Please do  mention any improvement ideas, especially considering naming the new module in a clear and concise way.

### CODE REVIEW

**Review by DM8AT — APPROVED** [review]
good to have some files for quartus that are set up correctly

**Comment by HrGaertner** [comment]
Whats the convention behind wires ending in "_" and those just ending in a normal letter?

**Comment by jon011235** [comment]
Is the convention with wire_name_ being low active documented? I think i did not see that in the coding style

**Comment by iJustLeyxo** [comment]
It can be found in the category "Code Formatting/Naming/Lowactivity"

**Pull request merged**
