### PR TITLE
Add utils

### PR DESCRIPTION
**Pull request by iJustLeyxo**
Add

- Clock enable generators
- PWM generator
- Counter

### CODE REVIEW

**Comment by HrGaertner** [comment]
For what do we need the pwm module?

**Comment by iJustLeyxo** [comment]
@HrGaertner fixing style issues rn, will answer in a few seconds

**Comment by HrGaertner** [comment]
Maybe rename clkgen2 to clksplit?
Since it is no generating an enable signal but slowing down the clock speed?

**Comment by iJustLeyxo** [comment]
@HrGaertner great idea. I'll do it right away! About the pwmgen, I think it is better to have it in the library even if it is not used until later. It would be nice to be able to control servos or similar via the microprocessor later on

**Review by jon011235 — APPROVED** [review]

**Pull request merged**
